initial version of izs-campus env
ipa320/cob_environments pull request #125
Opened 2017-08-09 12:38 UTC by ipa-bnm

2017-08-11 08:15 UTC, ipa-jba commented
fails due to missing "object_groups.yaml" for izs-* environments

```
-- run_tests.py: execute commands
  /usr/bin/cmake -E make_directory /root/catkin_ws/build/cob_default_env_config/test_results/cob_default_env_config
  /opt/ros/indigo/share/roslaunch/cmake/../scripts/roslaunch-check -o /root/catkin_ws/build/cob_default_env_config/test_results/cob_default_env_config/roslaunch-check___ROBOT_ENV_ipa-kitchen..xml /root/catkin_ws/src/cob_environments/cob_default_env_config/. ROBOT_ENV=ipa-kitchen
...writing test results to /root/catkin_ws/build/cob_default_env_config/test_results/cob_default_env_config/roslaunch-check___ROBOT_ENV_izs-carpark-top..xml
FAILURE:
[/root/catkin_ws/src/cob_environments/cob_default_env_config/./upload_object_locations.launch]:
	error loading <rosparam> tag: 
	file does not exist [/root/catkin_ws/src/cob_environments/cob_default_env_config/envs/izs-carpark-top/object_groups.yaml]
XML is <rosparam command="load" file="$(find cob_default_env_config)/envs/$(arg robot_env)/object_groups.yaml" ns="object_groups"/>
wrote test file to [/root/catkin_ws/build/cob_default_env_config/test_results/cob_default_env_config/roslaunch-check___ROBOT_ENV_izs-carpark-top..xml]
...writing test results to /root/catkin_ws/build/cob_default_env_config/test_results/cob_default_env_config/roslaunch-check___robot_env_izs-campus..xml
FAILURE:
[/root/catkin_ws/src/cob_environments/cob_default_env_config/./upload_object_locations.launch]:
	error loading <rosparam> tag: 
	file does not exist [/root/catkin_ws/src/cob_environments/cob_default_env_config/envs/izs-campus/object_groups.yaml]
XML is <rosparam command="load" file="$(find cob_default_env_config)/envs/$(arg robot_env)/object_groups.yaml" ns="object_groups"/>
wrote test file to [/root/catkin_ws/build/cob_default_env_config/test_results/cob_default_env_config/roslaunch-check___robot_env_izs-campus..xml]
checking *.launch in directory /root/catkin_ws/src/cob_environments/cob_default_env_config/.
...writing test results to /root/catkin_ws/build/cob_default_env_config/test_results/cob_default_env_config/roslaunch-check___robot_env_izs-carpark-top..xml
FAILURE:
[/root/catkin_ws/src/cob_environments/cob_default_env_config/./upload_object_locations.launch]:
	error loading <rosparam> tag: 
	file does not exist [/root/catkin_ws/src/cob_environments/cob_default_env_config/envs/izs-carpark-top/object_groups.yaml]
XML is <rosparam command="load" file="$(find cob_default_env_config)/envs/$(arg robot_env)/object_groups.yaml" ns="object_groups"/>
wrote test file to [/root/catkin_ws/build/cob_default_env_config/test_results/cob_default_env_config/roslaunch-check___robot_env_izs-carpark-top..xml]
checking /root/catkin_ws/src/cob_environments/cob_default_env_config/./upload_navigation_goals.launch
checking /root/catkin_ws/src/cob_environments/cob_default_env_config/./upload_object_locations.launch
...writing test results to /root/catkin_ws/build/cob_default_env_config/test_results/cob_default_env_config/roslaunch-check___ROBOT_ENV_izs-campus..xml
wrote test file to [/root/catkin_ws/build/cob_default_env_config/test_results/cob_default_env_config/roslaunch-check___ROBOT_ENV_izs-campus..xml]
FAILURE:
[/root/catkin_ws/src/cob_environments/cob_default_env_config/./upload_object_locations.launch]:
	error loading <rosparam> tag: 
	file does not exist [/root/catkin_ws/src/cob_environments/cob_default_env_config/envs/izs-campus/object_groups.yaml]
```

2017-08-11 09:19 UTC, ipa-jba commented
still missing for izs-carpark-top (shame on me for not enabling the tests when adding a new env)

2017-08-11 13:39 UTC, jabbenseth submitted a review, later dismissed

2017-08-21 07:49 UTC, ipa-fez submitted a review, later dismissed

2017-08-21 07:49 UTC, ipa-fez commented
@ipa-jba ping

2017-08-24 08:07 UTC, ipa-fke commented
Still WIP?

2017-08-24 10:49 UTC, stefandoerr approved these changes

2017-08-29 11:14 UTC, jabbenseth approved these changes

2017-08-29 11:14 UTC, ipa-jba commented on cob_default_env_config/envs/izs-campus/line_maps/lines_top_deck.yaml
> +
remove file? and cob_default_env_config/envs/izs-campus/line_maps/ground_marking.yaml

2017-08-29 13:25 UTC, jabbenseth requested changes
clumsy me approving while requesting changes

2017-09-01 11:08 UTC, ipa-bnm commented
ping @ipa-jba

2017-09-01 14:39 UTC, ipa-srd commented
ping @ipa-jba  could you review before you're gone for next week

2017-09-01 15:06 UTC, jabbenseth approved these changes

2017-09-04 08:06 UTC, merged