New map for ipa-office
ipa320/cob_environments pull request #128
Opened 2017-09-26 09:11 UTC by ipa-srd

Containing hallways of 4th floor of building E, transition hallway to building D, SR labs and some hallways of building D

2017-09-29 12:13 UTC, ipa-jba commented
Update the feature maps and path segments as well

2017-09-29 12:14 UTC, jabbenseth requested changes
Update the feature maps and path segments as well

2017-10-04 09:36 UTC, ipa-fez commented on cob_default_env_config/envs/ipa-office/point_maps/rfid_tags_ipa4thFloor.yaml
> +    description: imark_point_rfid_3
This can probably be removed too.

2017-10-04 10:25 UTC, jabbenseth approved these changes

2017-10-04 13:25 UTC, ipa-fez approved these changes

2017-10-04 13:30 UTC, merged